const BOOK_TYPE = 'book'
const FOOD_TYPE = 'food'
const MEDICAL_TYPE = 'medical'
const TECHNOLOGY_TYPE = 'tech'
const ITEM_TYPES_EXEMPTED_FROM_BASIC_TAX = [BOOK_TYPE, FOOD_TYPE, MEDICAL_TYPE]
const BASIC_SALES_TAX = 0.1
const IMPORT_TAX = 0.05

module.exports = {
    BOOK_TYPE,
    FOOD_TYPE,
    MEDICAL_TYPE,
    TECHNOLOGY_TYPE,
    ITEM_TYPES_EXEMPTED_FROM_BASIC_TAX,
    BASIC_SALES_TAX,
    IMPORT_TAX
}